{
 "title": "Apple Juice Factory",
 "description": "Demcon Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PackML States (ISA S88 Physical model)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Apple Juice Proceduced",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(caller)\nFROM etproceduralelementstates\nWHERE elementtypename = 'procedure' AND commandkey = 'Apple juice procedure' AND commandstate = 'Completed'"
    }
   ]
  },
  {
   "title": "Production Cell",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"PackML State\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell' AND statechangetime IS NOT NULL\nORDER BY statechangetime asc"
    }
   ]
  },
  {
   "title": "PackML states",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Apple_juice_mixer\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Apple_juice_mixer' AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY statechangetime ASC"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Vitamine_C_adder\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Vitamine_C_adder'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Apple_juice_mixer/Apple_juice_feeder\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Apple_juice_mixer/Apple_juice_feeder' AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Apple_juice_mixer/Sugar_solution_tank\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Apple_juice_mixer/Sugar_solution_tank' AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Apple_juice_mixer/Apple_juice_mixing_tank\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Apple_juice_mixer/Apple_juice_mixing_tank'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Apple_juice_mixer/Apple_juice_transfer_line\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Apple_juice_mixer/Apple_juice_transfer_line' AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Apple_juice_mixer/Apple_juice_feeder/Apple_juice_feeeder_pump\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Apple_juice_mixer/Apple_juice_feeder/Apple_juice_feeeder_pump'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Apple_juice_mixer/Apple_juice_feeder/Apple_juice_feeder_valve\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Apple_juice_mixer/Apple_juice_feeder/Apple_juice_feeder_valve'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Apple_juice_mixer/Sugar_solution_tank/Sugar_solution_feeder_pump\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Apple_juice_mixer/Sugar_solution_tank/Sugar_solution_feeder_pump'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Apple_juice_mixer/Sugar_solution_tank/Sugar_solution_feeder_valve\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Apple_juice_mixer/Sugar_solution_tank/Sugar_solution_feeder_valve'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Apple_juice_mixer/Apple_juice_mixing_tank/Apple_juice_mixing_agitator\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Apple_juice_mixer/Apple_juice_mixing_tank/Apple_juice_mixing_agitator'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Apple_juice_mixer/Apple_juice_mixing_tank/Apple_juice_cooler\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Apple_juice_mixer/Apple_juice_mixing_tank/Apple_juice_cooler'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Apple_juice_mixer/Apple_juice_transfer_line/Apple_juice_transfer_valve\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Apple_juice_mixer/Apple_juice_transfer_line/Apple_juice_transfer_valve'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Vitamine_C_adder/Vitamine_C_feeder_tank\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Vitamine_C_adder/Vitamine_C_feeder_tank'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Vitamine_C_adder/Vitamine_C_mixing_tank\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Vitamine_C_adder/Vitamine_C_mixing_tank'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Vitamine_C_adder/Mixed_apple_juice_transfer_line\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Vitamine_C_adder/Mixed_apple_juice_transfer_line'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Vitamine_C_adder/Vitamine_C_feeder_tank/Vitamine_C_pump\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Vitamine_C_adder/Vitamine_C_feeder_tank/Vitamine_C_pump'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Vitamine_C_adder/Vitamine_C_feeder_tank/Vitamine_C_valve\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Vitamine_C_adder/Vitamine_C_feeder_tank/Vitamine_C_valve'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Vitamine_C_adder/Vitamine_C_mixing_tank/Vitamine_c_mixing_agitator\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Vitamine_C_adder/Vitamine_C_mixing_tank/Vitamine_c_mixing_agitator'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Vitamine_C_adder/Vitamine_C_mixing_tank/Vitamine_C_cooler\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Vitamine_C_adder/Vitamine_C_mixing_tank/Vitamine_C_cooler'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  statechangetime AS \"time\",\n  newname AS \"Testmachine_Cell/Vitamine_C_adder/Mixed_apple_juice_transfer_line/Mixed_apple_juice_transfer_valve\"\nFROM etphysicalelementsstates\nWHERE treepath = 'Testmachine_Cell/Vitamine_C_adder/Mixed_apple_juice_transfer_line/Mixed_apple_juice_transfer_valve'AND newname IS NOT NULL AND statechangetime IS NOT NULL\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Procedural Elements (ISA S88 procedural model)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Procedures",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  statechangetime AS \"time\",\n  caller AS \"Caller\",\n  commandkey AS \"Command\",\n  commandstate AS \"State\",\n  CAST(result AS STRING) AS \"Result\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'procedure'\nORDER BY statechangetime DESC"
    }
   ]
  },
  {
   "title": "Unit Procedures",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  caller AS \"Caller\",\n  commandkey AS \"Command\",\n  commandstate AS \"State\",\n  CAST(result AS STRING) AS \"Result\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'unitProcedure'\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  caller AS \"Caller\",\n  commandkey AS \"Command\",\n  commandstate AS \"State\",\n  CAST(result AS STRING) AS \"Result\"\nFROM etproceduralelementstates\nWHERE elementtypename ='operation'\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Phases",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  caller AS \"Caller\",\n  commandkey AS \"Command\",\n  commandstate AS \"State\",\n  CAST(result AS STRING) AS \"Result\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'phase'\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Juice Producing (Procedure)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'procedure' AND commandkey = 'Apple juice procedure'\norder by statechangetime DESC\n"
    },
    {
     "rawSql": "SELECT COUNT(caller)\nFROM etproceduralelementstates\nWHERE elementtype = 'Unit Procedure' AND commandkey = 'Apple_Juice_mixing_unit_procedure' AND commandstate = 'Completed'"
    }
   ]
  },
  {
   "title": "Mix Juice (Unit Procedure)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'unitProcedure' AND commandkey = 'Apple_Juice_mixing_unit_procedure'\norder by time_index DESC limit 1"
    }
   ]
  },
  {
   "title": "Vitamine C added (Unit Procedure)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'unitProcedure' AND commandkey = 'Vitamine_C_addition_unit_procedure'\norder by time_index DESC limit 1"
    }
   ]
  },
  {
   "title": "Feed Juice (OP)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 65 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'operation' AND commandkey = 'Apple_juice_feed_operation'\norder by time_index DESC limit 1"
    }
   ]
  },
  {
   "title": "Transfer Juice (OP)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 65 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'operation' AND commandkey = 'Apple_juice_transfer_operation'\norder by time_index DESC limit 1"
    }
   ]
  },
  {
   "title": "Cool Juice(OP)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 65 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'operation' AND commandkey = 'Apple_juice_cooling_operation'\norder by time_index DESC limit 1"
    }
   ]
  },
  {
   "title": "Transfer Mixed Juice (OP)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 65 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'operation' AND commandkey = 'Mixed_apple_juice_transfer_operation'\norder by time_index DESC limit 1"
    }
   ]
  },
  {
   "title": "Cool Mixed Juice (OP)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 65 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'operation' AND commandkey = 'Mixed_apple_juice_cooling_operation'\norder by time_index DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Add Vitamine C (OP)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 65 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'operation' AND commandkey = 'Vitamine_C_addition_operation'\norder by time_index DESC limit 1"
    }
   ]
  },
  {
   "title": "Feed juice(Phase)",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 71 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'phase' AND commandkey = 'Feed_apple_juice_phase'\norder by time_index DESC limit 1"
    }
   ]
  },
  {
   "title": "Transfer juice(Phase)",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 71 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'phase' AND commandkey = 'transfer_apple_juice_phase'\norder by time_index DESC limit 1"
    }
   ]
  },
  {
   "title": "Cool juice(Phase)",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 71 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'phase' AND commandkey = 'Cool_apple_juice_phase'\norder by time_index DESC limit 1\n"
    }
   ]
  },
  {
   "title": "Transfer mixed juice(Phase)",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 71 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'phase' AND commandkey = 'Transfer_mixed_apple_juice_phase'\norder by time_index DESC limit 1"
    }
   ]
  },
  {
   "title": "Cool Mixed juice(Phase)",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 71 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'phase' AND commandkey = 'Cool_mixed_apple_juice_phase'\norder by time_index DESC limit 1"
    }
   ]
  },
  {
   "title": "Agitate mixed juice(Phase)",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 71 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'phase' AND commandkey = 'Agitate_mixed_apple_juice_phase'\norder by time_index DESC limit 1"
    }
   ]
  },
  {
   "title": "Feed Sugar (Phase)",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 74 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'phase' AND commandkey = 'Feed_sugar_solution_phase'\norder by time_index DESC limit 1"
    }
   ]
  },
  {
   "title": "Add Vitamine C(Phase)",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 74 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'phase' AND commandkey = 'Add_vitamine_C_pahse'\norder by time_index DESC limit 1"
    }
   ]
  },
  {
   "title": "Agitate Juice (Phase)",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 77 },
   "targets": [
    {
     "rawSql": "SELECT \n  statechangetime AS time,\n  commandstate AS \"State\"\nFROM etproceduralelementstates\nWHERE elementtypename = 'phase' AND commandkey = 'Agitate_apple_juice_phase'\norder by time_index DESC limit 1"
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "All commands",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  caller AS \"caller\",\n  executer AS \"Executer\",\n  commandkey AS \"Command\",\n  commandstate AS \"State\",\n  CAST(result AS STRING) AS \"Result\",\n  CAST(duration AS STRING) AS \"Duration\"\nFROM ettelemetryvalues\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Failed commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  caller AS \"caller\",\n  executer AS \"Executer\",\n  commandkey AS \"Command\",\n  commandstate AS \"State\",\n  CAST(result AS STRING) AS \"Result\",\n  CAST(duration AS STRING) AS \"Duration\"\nFROM ettelemetryvalues\nWHERE result <> 0 AND result <> 2147483647\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Telemetry (Continuous sensor data)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 }
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time_index AS \"time\",\n  CAST(value AS FLOAT) AS \"Testmachine_Cell/Vitamine_C_adder/Vitamine_C_mixing_tank\"\nFROM ettelemetryvalues\nWHERE treepath = 'Testmachine_Cell/Vitamine_C_adder/Vitamine_C_mixing_tank'\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT \n  time_index AS \"time\",\n  CAST(value AS FLOAT) AS \"Testmachine_Cell/Apple_juice_mixer/Apple_juice_mixing_tank\"\nFROM ettelemetryvalues\nWHERE treepath = 'Testmachine_Cell/Apple_juice_mixer/Apple_juice_mixing_tank'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  time_index AS \"time\",\n  CAST(value AS FLOAT) AS \"Vitamine C mixing tank\"\nFROM ettelemetryvalues\nWHERE treepath = 'Testmachine_Cell/Vitamine_C_adder/Vitamine_C_mixing_tank'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT \n  time_index AS \"time\",\n  CAST(value AS FLOAT) AS \"Apple juice mixing tank\"\nFROM ettelemetryvalues\nWHERE treepath = 'Testmachine_Cell/Apple_juice_mixer/Apple_juice_mixing_tank'\nORDER BY 1"
    }
   ]
  },
  { "title": "Events (abnormalities)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "rawSql": "SELECT \n  lastchangetime AS \"time\",\n  uid AS \"UID\",\n  description AS \"Description\"\nFROM ettelemetryvalues\nORDER BY lastchangetime desc"
    }
   ]
  }
 ]
}